require("ifj.plugins-setup")
require("ifj.core.keymaps")
require("ifj.plugins.comment")
require("ifj.plugins.nvim-tree")
require("ifj.plugins.lualine")
require("ifj.plugins.telescope")
require("ifj.plugins.nvim-cmp")
require("ifj.plugins.lsp.mason")
require("ifj.plugins.lsp.lspsaga")
require("ifj.plugins.lsp.lspconfig")
require("ifj.plugins.lsp.null-ls")
require("ifj.plugins.autopairs")
require("ifj.plugins.treesitter")
require("ifj.plugins.gitsigns")
require("ifj.plugins.rest")
require("ifj.core.colorscheme")
require("ifj.core.options")

vim.cmd("set verbosefile=~/nvim.log")
vim.cmd("set verbose=10")
